#pragma once

#include "lvgl.h"

/* Montserrat + Latin Extended-A (Polish diacritics) + LVGL symbols,
 * generated by lv_font_conv (see tools/gen_fonts.sh). */
extern const lv_font_t font_pl_14;
extern const lv_font_t font_pl_16;
extern const lv_font_t font_pl_20;
